/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.pp.bizon.sunc.ui;

import javax.swing.SwingUtilities;

import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

/**
 * 
 * @author roman
 */
public class SuncFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -8392175911903948881L;

    @Autowired
    private SuncFrameBean bean;

    @Autowired
    private ApplicationContext context;

    /**
     * Creates new form SuncFrame
     */
    public SuncFrame() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoggerFactory.getLogger(getClass()).trace("SuncFrame context");
                while (context == null){
                    Thread.yield();
                }
                LoggerFactory.getLogger(getClass()).trace("SuncFrame context inited");
                initComponents();
                LoggerFactory.getLogger(getClass()).trace("SuncFrame context up");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        leftFilePanel = getLeftFilePanel();
        rightFilePanel = getRightFilePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        leftMenu = new javax.swing.JMenu();
        leftLocalMenuItem = new javax.swing.JMenuItem();
        leftRemoteMenuItem = new javax.swing.JMenuItem();
        rightMenu = new javax.swing.JMenu();
        rightLocalMenuItem = new javax.swing.JMenuItem();
        rigthRemoteMenuItem = new javax.swing.JMenuItem();
        SuncMenu = new javax.swing.JMenu();
        LeftToRightMenuItem = new javax.swing.JMenuItem();
        RightToLeftMenuItem = new javax.swing.JMenuItem();
        doubleSuncMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
                { null, null, null }, { null, null, null }, { null, null, null } }, new String[] { "Title 1",
                "Title 2", "Title 3" }));
        jScrollPane1.setViewportView(jTable1);

        leftMenu.setText("Left");

        leftLocalMenuItem.setText("Local");
        leftLocalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftLocalMenuItemActionPerformed(evt);
            }
        });
        leftMenu.add(leftLocalMenuItem);

        leftRemoteMenuItem.setText("Remote");
        leftRemoteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRemoteMenuItemActionPerformed(evt);
            }
        });
        leftMenu.add(leftRemoteMenuItem);

        jMenuBar1.add(leftMenu);

        rightMenu.setText("Right");

        rightLocalMenuItem.setText("Local");
        rightLocalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightLocalMenuItemActionPerformed(evt);
            }
        });
        rightMenu.add(rightLocalMenuItem);

        rigthRemoteMenuItem.setText("Remote");
        rigthRemoteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rigthRemoteMenuItemActionPerformed(evt);
            }
        });
        rightMenu.add(rigthRemoteMenuItem);

        jMenuBar1.add(rightMenu);

        SuncMenu.setText("Sunc");

        LeftToRightMenuItem.setText("Left to Rigth");
        LeftToRightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftToRightMenuItemActionPerformed(evt);
            }
        });
        SuncMenu.add(LeftToRightMenuItem);

        RightToLeftMenuItem.setText("Right to Left");
        RightToLeftMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightToLeftMenuItemActionPerformed(evt);
            }
        });
        SuncMenu.add(RightToLeftMenuItem);

        doubleSuncMenuItem.setText("Both");
        doubleSuncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSuncMenuItemActionPerformed(evt);
            }
        });
        SuncMenu.add(doubleSuncMenuItem);

        jMenuBar1.add(SuncMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout.createSequentialGroup().addContainerGap()
                                                        .addComponent(jScrollPane1))
                                        .addGroup(
                                                layout.createSequentialGroup()
                                                        .addComponent(leftFilePanel,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rightFilePanel,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(leftFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 342,
                                                Short.MAX_VALUE)
                                        .addComponent(rightFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FilePanel getRightFilePanel() {
        return context.getBean("FilePanelRight", FilePanel.class);
    }

    private FilePanel getLeftFilePanel() {
       return context.getBean("FilePanelLeft", FilePanel.class);
    }

    private void rigthRemoteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rigthRemoteMenuItemActionPerformed
        rightFilePanel.update(Direction.Remote);
    }// GEN-LAST:event_rigthRemoteMenuItemActionPerformed

    private void leftLocalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_leftLocalMenuItemActionPerformed
        leftFilePanel.update(Direction.Local);
    }// GEN-LAST:event_leftLocalMenuItemActionPerformed

    private void leftRemoteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_leftRemoteMenuItemActionPerformed
        leftFilePanel.update(Direction.Remote);
    }// GEN-LAST:event_leftRemoteMenuItemActionPerformed

    private void rightLocalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rightLocalMenuItemActionPerformed
        rightFilePanel.update(Direction.Local);
    }// GEN-LAST:event_rightLocalMenuItemActionPerformed

    private void LeftToRightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LeftToRightMenuItemActionPerformed
        bean.getJobs().addJob(Direction.LeftToRigth, leftFilePanel.getSelected(), rightFilePanel.getSelected());
    }// GEN-LAST:event_LeftToRightMenuItemActionPerformed

    private void RightToLeftMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RightToLeftMenuItemActionPerformed
        bean.getJobs().addJob(Direction.RigthToLeft, leftFilePanel.getSelected(), rightFilePanel.getSelected());
    }// GEN-LAST:event_RightToLeftMenuItemActionPerformed

    private void doubleSuncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doubleSuncMenuItemActionPerformed
        bean.getJobs().addJob(Direction.Both, leftFilePanel.getSelected(), rightFilePanel.getSelected());
    }// GEN-LAST:event_doubleSuncMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LeftToRightMenuItem;
    private javax.swing.JMenuItem RightToLeftMenuItem;
    private javax.swing.JMenu SuncMenu;
    private javax.swing.JMenuItem doubleSuncMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private ua.pp.bizon.sunc.ui.FilePanel leftFilePanel;
    private javax.swing.JMenuItem leftLocalMenuItem;
    private javax.swing.JMenu leftMenu;
    private javax.swing.JMenuItem leftRemoteMenuItem;
    private ua.pp.bizon.sunc.ui.FilePanel rightFilePanel;
    private javax.swing.JMenuItem rightLocalMenuItem;
    private javax.swing.JMenu rightMenu;
    private javax.swing.JMenuItem rigthRemoteMenuItem;
    // End of variables declaration//GEN-END:variables
}
